<?xml version="1.0"?>
<testsuite name='Titan' tests='22' failures='5' errors='2' skipped='0' inconc='0' time='MASKED'>
  <testcase classname='SGSN_Tests' name='TC_attach' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_mnc3' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_auth_id_timeout' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_auth_sai_timeout' time='MASKED'>
    <failure type='fail-verdict'>Tguard timeout
      SGSN_Tests.ttcn:MASKED SGSN_Tests control part
      SGSN_Tests.ttcn:MASKED TC_attach_auth_sai_timeout testcase
    </failure>
  </testcase>
  <testcase classname='SGSN_Tests' name='TC_attach_auth_sai_reject' time='MASKED'>
    <failure type='fail-verdict'>Tguard timeout
      SGSN_Tests.ttcn:MASKED SGSN_Tests control part
      SGSN_Tests.ttcn:MASKED TC_attach_auth_sai_reject testcase
    </failure>
  </testcase>
  <testcase classname='SGSN_Tests' name='TC_attach_gsup_lu_timeout' time='MASKED'>
    <failure type='fail-verdict'>Tguard timeout
      SGSN_Tests.ttcn:MASKED SGSN_Tests control part
      SGSN_Tests.ttcn:MASKED TC_attach_gsup_lu_timeout testcase
    </failure>
  </testcase>
  <testcase classname='SGSN_Tests' name='TC_attach_gsup_lu_reject' time='MASKED'>
    <failure type='fail-verdict'>Tguard timeout
      SGSN_Tests.ttcn:MASKED SGSN_Tests control part
      SGSN_Tests.ttcn:MASKED TC_attach_gsup_lu_reject testcase
    </failure>
  </testcase>
  <testcase classname='SGSN_Tests' name='TC_attach_combined' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_accept_all' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_closed' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_rau_unknown' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_rau' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_detach_unknown_nopoweroff' time='MASKED'>
    <error type='DTE'>Dynamic test case error: Error message was received from MC: The connect operation refers to test component with component reference 77, which has already terminated.</error>
  </testcase>
  <testcase classname='SGSN_Tests' name='TC_detach_unknown_poweroff' time='MASKED'>
    <error type='DTE'>Dynamic test case error: Error message was received from MC: The connect operation refers to test component with component reference 83, which has already terminated.</error>
  </testcase>
  <testcase classname='SGSN_Tests' name='TC_detach_nopoweroff' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_detach_poweroff' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_pdp_act' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_pdp_act_unattached' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_pdp_act_user' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_pdp_act_ggsn_reject' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_pdp_act_user_deact_mo' time='MASKED'/>
  <testcase classname='SGSN_Tests' name='TC_attach_pdp_act_user_deact_mt' time='MASKED'>
    <failure type='fail-verdict'>Tguard timeout
      SGSN_Tests.ttcn:MASKED SGSN_Tests control part
      SGSN_Tests.ttcn:MASKED TC_attach_pdp_act_user_deact_mt testcase
    </failure>
  </testcase>
</testsuite>
